steps:       
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/anthos-orders:$TAG_NAME','orders/.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/anthos-orders:$TAG_NAME']

- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', '--force' , '--set', 'imagetag=$TAG_NAME', 'ordersdeprel-$TAG_NAME', './orders/ordersdepchart', '--namespace', 'default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'

- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', '--force' , '--set', 'imagetag=$TAG_NAME', 'orderssvcrel', './orders/orderssvcchart', '--namespace', 'default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
