apiVersion: v1
kind: Service
metadata:
  name: frontend-ser
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-port
      protocol: TCP
      targetPort: 80
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
       app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec: 
      containers:
        - name: frontend
          image: gcr.io/gcdeveloper/anthos-frontend:1.7.0  