apiVersion: v1
kind: Service
metadata:
  name: customer-detail-ser
  labels:
     app: customer-detail-be
spec:
  type: NodePort
  selector:
    app: customer-detail-be
  ports:
    - name: tcp-custdetail
      protocol: TCP
      targetPort: 9000
      port: 9000