apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }} 
  labels:
    app: {{ .Values.appname }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - name: tcp-customer
      port: 9000