apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: classicmodels
  DB_USER: anthos
  DB_HOST: anthos-mysql
  PORT: "9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pass
data:
  DB_PASS: YWJjMTIz
---
apiVersion: v1
kind: Service
metadata:
  name: customer-ser
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: customer-be
  ports:
    - name: customer-be-port
      protocol: TCP
      targetPort: 9000
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-dep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
       app: customer-be
  template:
    metadata:
      name: customer-be
      labels:
        app: customer-be
    spec: 
      containers:
        - name: customer-be
          image: gcr.io/gcdeveloper/anthos-customer:{{ .Values.imagetag }}
          envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: db-pass    
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metric-sd
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-dep
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: External
    external:
      metricName: prometheus|custsvc_total_requests
      targetAverageValue: 15
