steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['source', 'repos', 'clone', 'anthos-poc']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcdeveloper/anthos-customer:$TAG_NAME','customer/.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcdeveloper/anthos-customer:$TAG_NAME']

- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', '--force' , '--set', 'imagetag=$TAG_NAME', 'custsvcrel', './customer/custsvcchart', '--namespace', 'default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
  