apiVersion: v1
kind: Service
metadata:
  name: anthos-mysql
  labels:
    app: anthos-db
spec:
  ports:
    - port: 3306
      name: tcp-mysql
  selector:
    app: anthos-db
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: YWJjMTIz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: anthos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: anthos-mysql
  labels:
    app: anthos-db
spec:
  selector:
    matchLabels:
      app: anthos-db
      version: v5.6
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anthos-db
        version: v5.6
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: tcp-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim