apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-{{ .Release.Name }}
data:
  DB_NAME: classicmodels
  DB_USER: anthos
  DB_HOST: anthos-mysql
  CLUSTER_NAME: {{ .Values.cluster_name }}
  PROJECT_ID: {{ .Values.project_id }}
  SERVICE_NAME: {{ .Values.service_name }}
  REGION: {{ .Values.region }}
  PORT: "9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pass-{{ .Release.Name }}
data:
  DB_PASS: YWJjMTIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-detail-dep-{{ .Values.imagetag }}
  labels:
    app: {{ .Values.appname }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
       app: {{ .Values.appname }}
       version: {{ .Values.imagetag }}
  template:
    metadata:
      name: {{ .Values.appname }}
      labels:
        app: {{ .Values.appname }}
        version: {{ .Values.imagetag }}
    spec: 
      containers:
        - name: {{ .Values.appname }}
          image: gcr.io/{{ .Values.project_id }}/anthos-customer-detail:{{ .Values.imagetag }}
          ports:
            - containerPort: 9000
              name: tcp-custdetail
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid   
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace                  
          envFrom:
          - configMapRef:
                name: db-config-{{ .Release.Name }}
          - secretRef:
                 name: db-pass-{{ .Release.Name }}   
