apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-{{ .Release.Name }}
data:
  DB_NAME: classicmodels
  DB_USER: anthos
  DB_HOST: anthos-mysql
  CLUSTER_NAME: {{ .Values.cluster_name }}
  PROJECT_ID: {{ .Values.project_id }}
  SERVICE_NAME: {{ .Values.service_name }}
  REGION: {{ .Values.region }}
  PORT: "9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pass-{{ .Release.Name }}
data:
  DB_PASS: YWJjMTIz
---
apiVersion: v1
kind: Service
metadata:
  name: customer-detail-ser
spec:
  type: NodePort
  selector:
    app: customer-detail-be
  ports:
    - name: customer-detail-be-port
      protocol: TCP
      targetPort: 9000
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-detail-dep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
       app: customer-detail-be
  template:
    metadata:
      name: customer-detail-be
      labels:
        app: customer-detail-be
    spec: 
      containers:
        - name: customer-detail-be
          image: gcr.io/{{ .Values.project_id }}/anthos-customer-detail:{{ .Values.imagetag }}
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid   
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace                  
          envFrom:
          - configMapRef:
                name: db-config-{{ .Release.Name }}
          - secretRef:
                 name: db-pass-{{ .Release.Name }}   
