apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }} 
  labels:
     app: {{ .Values.appname }}
     service: {{ .Values.appname }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - name: http
      port: 9000