apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }} 
  labels:
     app: {{ .Values.appname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appname }}
  ports:
    - name: tcp-custdetail
      protocol: TCP
      targetPort: 9000
      port: 9000